{% set name = "tip" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/309thEDDGE/tip/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 0e818cea2d468de790e232bc7adda521998fafe587d94615d46efef52d140a83
 
build:
  skip: true  # [win and vc<14 or osx]
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - ninja 1.*
    - cmake 3.*
    - pkgconfig 1.*

  host:
    - arrow-cpp
    - spdlog
    - yaml-cpp
    - gmock
    - gtest
    - libtins
    - fmt

  run:
    - gmock
    - gtest

test:
  commands:
    - tests
    - tip parse -h
    - tip translate 1553 -h
    - tip translate arinc429 -h
    - tip util vidextract -h
    - tip util pqcomp -h
    - tip util bincomp -h
    - tip util validyaml -h

about:
  home: https://github.com/309thEDDGE/tip.git
  summary: 'Fast IRIG 106 Chapter 10 CLI parser/translator'
  description: |
    Parse IRIG 106 Chapter 10 and export parsed, raw data to Parquet.
    In a second (translation) stage, convert raw data to Engineering Units 
    (EU, ft, m/s, etc.) given an input file which conveys Interface Control Document 
    (ICD) data.  
  license: GPL-3.0-only AND BSD-4-Clause-UC
  license_file: licenses/
  dev_url: https://github.com/309thEDDGE/tip.git

extra:
  recipe-maintainers:
    - IM-USAF
    - RR-USAF
    - JR-USAF
